
import os


def explore_data(df):
    print("\n" + "=" * 50)
    print("  DATA EXPLORATION REPORT")
    print("=" * 50)
    print(f"  Rows        : {df.shape[0]}")
    print(f"  Columns     : {df.shape[1]}")
    print(f"\n  Column Names: {list(df.columns)}")
    print(f"\n  Data Types:")
    for col, dtype in df.dtypes.items():
        print(f"    {col}: {dtype}")
    print(f"\n  Missing Values:")
    for col, count in df.isnull().sum().items():
        print(f"    {col}: {count}")
    print(f"\n  Duplicate Rows: {df.duplicated().sum()}")
    print("=" * 50)


def generate_statistics(df):
    print("\n" + "=" * 50)
    print("  SUMMARY STATISTICS")
    print("=" * 50)
    print(f"  Total Rows    : {len(df)}")
    print(f"  Total Columns : {len(df.columns)}")

    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
    text_cols = df.select_dtypes(include=["object"]).columns

    if len(numeric_cols) > 0:
        print(f"\n  Numeric Columns:")
        for col in numeric_cols:
            print(f"\n    {col}:")
            print(f"      Average : {round(df[col].mean(), 2)}")
            print(f"      Highest : {df[col].max()}")
            print(f"      Lowest  : {df[col].min()}")
            print(f"      Total   : {df[col].sum()}")

    if len(text_cols) > 0:
        print(f"\n  Text Columns:")
        for col in text_cols:
            print(f"\n    {col}:")
            print(f"      Unique Values : {df[col].nunique()}")
            print(f"      Most Common   : {df[col].mode()[0]}")

    print("=" * 50)


def export_report(df, output_path):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
    text_cols = df.select_dtypes(include=["object"]).columns

    with open(output_path, "w") as f:
        f.write("=" * 50 + "\n")
        f.write("  EXCEL AUTOMATION SUITE - SUMMARY REPORT\n")
        f.write("=" * 50 + "\n\n")

        f.write(f"Total Rows    : {len(df)}\n")
        f.write(f"Total Columns : {len(df.columns)}\n\n")

        if len(numeric_cols) > 0:
            f.write("Numeric Column Statistics:\n")
            for col in numeric_cols:
                f.write(f"\n  {col}:\n")
                f.write(f"    Average : {round(df[col].mean(), 2)}\n")
                f.write(f"    Highest : {df[col].max()}\n")
                f.write(f"    Lowest  : {df[col].min()}\n")
                f.write(f"    Total   : {df[col].sum()}\n")

        if len(text_cols) > 0:
            f.write("\nText Column Summaries:\n")
            for col in text_cols:
                f.write(f"\n  {col}:\n")
                f.write(f"    Unique Values : {df[col].nunique()}\n")
                f.write(f"    Most Common   : {df[col].mode()[0]}\n")

        f.write("\n" + "=" * 50 + "\n")
        f.write("Report generated by Excel Automation Suite\n")

    print(f"  Report saved: {output_path}")

def explore_data_dict(df):
    missing = {col: int(count) for col, count in df.isnull().sum().items()}
    dtypes = {col: str(dtype) for col, dtype in df.dtypes.items()}
    return {
        "rows": df.shape[0],
        "columns": df.shape[1],
        "column_names": list(df.columns),
        "missing_values": missing,
        "duplicates": int(df.duplicated().sum()),
        "dtypes": dtypes
    }


def generate_statistics_dict(df):
    numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
    text_cols = df.select_dtypes(include=["object"]).columns

    numeric_stats = {}
    for col in numeric_cols:
        numeric_stats[col] = {
            "average": round(float(df[col].mean()), 2),
            "highest": int(df[col].max()),
            "lowest": int(df[col].min()),
            "total": int(df[col].sum())
        }

    text_stats = {}
    for col in text_cols:
        text_stats[col] = {
            "unique": int(df[col].nunique()),
            "most_common": str(df[col].mode()[0])
        }

    return {
        "numeric": numeric_stats,
        "text": text_stats,
        "total_rows": len(df),
        "total_columns": len(df.columns)
    }